# Zoostudios backend — multi-service provisioning API
FROM node:22-alpine AS base
RUN npm config set registry https://registry.npmmirror.com && npm i -g pnpm@9.15.9
# registry mirror also serves prisma engines (binaries.prisma.sh is not reachable here)
ENV PRISMA_ENGINES_MIRROR=https://registry.npmmirror.com/-/binary/prisma
WORKDIR /app

# dependencies (dev deps included: needed for prisma generate + seed via ts-node)
COPY package.json pnpm-lock.yaml ./
# schema needed BEFORE install: the package postinstall runs `prisma generate`
COPY prisma ./prisma
RUN pnpm config set registry https://registry.npmmirror.com \
 && pnpm config set fetch-retries 5 \
 && pnpm config set fetch-retry-mintimeout 20000 \
 && pnpm install --no-frozen-lockfile

# prisma client was generated by postinstall; now add the source and build
COPY . .
# stale incremental build info makes tsc silently skip emit — remove before building
RUN rm -f tsconfig*.tsbuildinfo \
 && ./node_modules/.bin/nest build \
 && rm -f tsconfig*.tsbuildinfo \
 && test -f dist/main.js \
 && test -f dist/config/configuration.js \
 && echo "backend build verified: dist/main.js + dist/config/configuration.js present"

# runtime
EXPOSE 3000
ENV NODE_ENV=production
ENTRYPOINT ["./docker-entrypoint.sh"]
