name: production
variables:
  - name: baseUrl
    value: https://cloud.thirdparties.airpass.co.tz
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXR3eHFhdzgwMDAwczQxaGcyM25oczZkIiwiZW1haWwiOiJkaXJlY3RvckB6b29mYW0uY28udHoiLCJuYW1lIjoiZGlyZWN0b3IiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODk0NTg5MzYsImV4cCI6MTc4OTQ4NzczNn0.obqQByfs5E_ZWJ3bpMbn5OnVjmBaHlSvTBI49s4mq6U
  - name: apiKey
    value: PASTE_API_KEY_MIN_32_CHARS
  - name: accountId
    value: PASTE_ACCOUNT_PUBLIC_ID
  - name: keyId
    value: PASTE_API_KEY_ID_TO_REVOKE
  - name: planId
    value: PASTE_PLAN_ID
  - name: billId
    value: PASTE_BILL_ID
  - name: webhookEndpointId
    value: PASTE_WEBHOOK_ENDPOINT_ID
  - name: collectionReference
    value: PASTE_20_CHAR_COLLECTION_REF
  - name: payoutReference
    value: PASTE_20_CHAR_PAYOUT_REF
  - name: batchReference
    value: PASTE_20_CHAR_BATCH_REF
  - name: smsReference
    value: PASTE_20_CHAR_SMS_REF
  - name: adminEmail
    value: director@zoofam.co.tz
  - name: adminPassword
    value: dstech876543211
