/** Stable error codes surfaced in every error response for frontend clarity. */
export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  SERVICE_NOT_GRANTED: 'SERVICE_NOT_GRANTED',
  CHANNEL_NOT_ALLOWED: 'CHANNEL_NOT_ALLOWED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_ACTIONS_NOT_GRANTED: 'WALLET_ACTIONS_NOT_GRANTED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  DUPLICATE_REFERENCE: 'DUPLICATE_REFERENCE',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
  INVALID_SENDER: 'INVALID_SENDER',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const SERVICE_KEYS = ['COLLECTION', 'DISBURSEMENT', 'SMS'] as const;
export type ServiceKeyValue = (typeof SERVICE_KEYS)[number];
